### PR TITLE
feat: add support for object types

### PR DESCRIPTION
**Pull request by kirederik**
- **fix: add a line break**
- **feat(update api): support for object type**

### CODE REVIEW

**Review by ChunyiLyu — COMMENTED** [review]
Looks good just something minor:
1. perhaps add an example to `kratix update api` help message

2. I can add nested field to a non object property like:
```
kratix update api -p config.f1.f2:string
cat api.yaml
...
          spec:
            properties:
              config:
                properties:
                  f1:
                    properties:
                      f2:
                        type: string
                    type: object
                type: object
            type: object
        type: object

kratix update api -p config.f1.f2.f3:integer
cat api.yaml
...
spec:
...
        properties:
          spec:
            properties:
              config:
                properties:
                  f1:
                    properties:
                      f2:
                        properties:
                          f3:
                            type: integer
                        type: object
                    type: object
                type: object
            type: object
        type: object
```

Since `config.f1.f2` is of `string`, I was expecting an error, but adding `config.f1.f2.f3` succeeded and changed type of `config.f1.f2` from string to object.

**Comment by kirederik** [comment]
>Since config.f1.f2 is of string, I was expecting an error, but adding config.f1.f2.f3 succeeded and changed type of config.f1.f2 from string to object.

Yeah, and that was implemented like that on purpose 👀 
I was in two minds on whether to fail or to update the "parent" type. I decided for the latter since I deemed it more consistent with the command behaviour when you change the type.

For example, running the command below works (foo type will change to string from integer)

```
kratix update api -p foo:integer
kratix update api -p foo:string
```

So running:

```
kratix update api -p foo:string
kratix update api -p foo.subFoo:string # this is implicitly the same as running `-p foo:object -p foo.subFoo:string`
```

should also work, by converting foo to `object` and adding `subFoo` as string.

By induction, it should also work for 

```
kratix update api -p foo.subFoo:string
kratix update api -p foo.subFoo.subSubFoo:string
```

We could force the conversion to object to be an explicit step, but that felt unecessary.

thoughts? 👀

**Comment by kirederik** [comment]
added the example to the readme!

**Review by ChunyiLyu — APPROVED** [review]

**Comment by ChunyiLyu** [comment]
@kirederik sounds good and just approved 😀

**Pull request merged**
